llmos-ai/dashboard

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/SingleClusterInfo.vue
- shell/config/product/llm.js
- shell/config/types.js
- shell/edit/ml.llmos.ai.notebook.vue
- shell/edit/ray.io.raycluster.vue
- shell/list/ml.llmos.ai.modelfile.vue
- shell/list/ml.llmos.ai.notebook.vue
- shell/list/ray.io.raycluster.vue
- shell/pages/c/_cluster/llm/index.vue
- Add GPU and advanced pages that are needed for ML management.
> feat: add gpu and advanced pages

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/ContainerResourceLimit.vue
- shell/components/SingleClusterInfo.vue
- shell/components/form/EnvVars.vue
- shell/components/form/NodeScheduling.vue
- shell/components/form/ResourceTabs/index.vue
- shell/components/form/ValueFromResource.vue
- shell/config/product/llm.js
- shell/config/types.js
- shell/edit/ml.llmos.ai.modelservice/index.vue
- shell/edit/ml.llmos.ai.notebook.vue
- shell/edit/ray.io.raycluster.vue
- shell/edit/volume/emptyDir.vue
- shell/edit/volume/index.vue
- shell/edit/volume/persistentVolumeClaim/index.vue
- shell/edit/volume/persistentVolumeClaim/persistentvolumeclaim.vue
- shell/list/ml.llmos.ai.modelfile.vue
- shell/list/ml.llmos.ai.modelservice.vue
- shell/list/ml.llmos.ai.notebook.vue
- shell/list/ray.io.raycluster.vue
- shell/mixins/llmos-workload.js
- shell/models/ml.llmos.ai.modelservice.js
- shell/models/ml.llmos.ai.notebook.js
Add model service page and few fix translation
> Add model service page and few fix translation

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/GlobalRoleBindings.vue
- shell/components/auth/RoleDetailEdit.vue
- shell/components/nav/Header.vue
- shell/components/nav/TopLevelMenu.vue
- shell/config/product/auth.js
- shell/config/product/llmos.js
- shell/config/router.js
- shell/config/types.js
- shell/detail/management.llmos.ai.globalrole.vue
- shell/edit/management.llmos.ai.globalrole.vue
- shell/edit/management.llmos.ai.roletemplate.vue
- shell/edit/management.llmos.ai.user.vue
- shell/layouts/default.vue
- shell/list/management.llmos.ai.token.vue
- shell/list/management.llmos.ai.user.vue
- shell/models/management.llmos.ai.globalrole.js
- shell/models/management.llmos.ai.user.js
- shell/models/rbac.authorization.k8s.io.clusterrole.js
- shell/models/rbac.authorization.k8s.io.role.js
- shell/pages/c/_cluster/auth/roles/_resource/_id.vue
- shell/pages/c/_cluster/auth/roles/_resource/create.vue
- shell/pages/c/_cluster/auth/roles/index.vue
- shell/plugins/steve/subscribe.js
- shell/store/index.js
- shell/store/store-types.js
Add user RBAC & global roles template.
> Add user rbac & role templates

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/ResourceSummary.vue
- shell/components/SingleClusterInfo.vue
- shell/components/nav/TopLevelMenu.vue
- shell/config/router.js
- shell/models/management.llmos.ai.user.js
- shell/pages/auth/login.vue
- shell/pages/auth/setup.vue
Add auth setup page for the user's first login.
> Aadd auth setup page for first-login

- shell/edit/management.llmos.ai.managedaddon.vue
- shell/layouts/default.vue
- shell/models/management.llmos.ai.token.js
- shell/plugins/dashboard-store/actions.js
- shell/plugins/steve/accept-or-reject-socket-message.ts
- shell/plugins/steve/projectAndNamespaceFiltering.utils.ts
- shell/plugins/steve/subscribe.js
- shell/store/type-map.utils.ts
- shell/utils/gc/gc-interval.ts
- shell/utils/gc/gc-root-store.js
- shell/utils/gc/gc-route-changed.ts
- shell/utils/gc/gc-types.ts
- shell/utils/gc/gc.ts
- shell/utils/socket.js
Fix WebSocket uses too old version.
> fix  websocket uses too old version

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/BrandImage.vue
- shell/components/nav/Header.vue
- shell/components/nav/NamespaceFilter.vue
- shell/components/nav/TopLevelMenu.vue
- shell/config/private-label.js
- shell/config/settings.ts
- shell/pages/about.vue
- shell/pages/auth/login.vue
- shell/pages/prefs.vue
- shell/store/auth.js
- shell/store/index.js
- shell/store/prefs.js
Update UI settings & private label configs
> Update UI settings & private label configs

- README.md
- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/config/settings.ts
- shell/edit/management.llmos.ai.setting.vue
- shell/list/management.llmos.ai.setting.vue
- shell/pages/auth/login.vue
- shell/store/auth.js
Fixes auth and add new settings
> fix auth and add new settings

- shell/config/labels-annotations.js
- shell/detail/ml.llmos.ai.modelservice.vue
- shell/detail/ml.llmos.ai.notebook.vue
- shell/edit/ml.llmos.ai.modelservice/index.vue
- shell/edit/volume/index.vue
- shell/edit/volume/persistentVolumeClaim/index.vue
- shell/list/ml.llmos.ai.modelservice.vue
- shell/mixins/llmos-workload.js
- shell/models/llmos-workload.js
- shell/models/ml.llmos.ai.modelservice.js
- shell/models/ml.llmos.ai.notebook.js
- shell/plugins/steve/subscribe.js
- shell/utils/selector.js
- update model service detail page & fix errors
- add notebooks detail page
- fix ws is not subscribed properly.
> Fix model service, notebook & ws

- shell/list/ml.llmos.ai.modelservice.vue
- shell/list/ml.llmos.ai.notebook.vue
- shell/models/llmos-workload.js
- shell/models/ml.llmos.ai.modelservice.js
Small enhancement for model service & notebook workload.
> Small enhancement for ms & notebook workload

- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- README.md
> Update CI lint flow

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/NodeImportCommand.vue
- shell/components/ResourceList/Masthead.vue
- shell/components/ResourceList/index.vue
- shell/config/elemental-types.js
- shell/config/labels-annotations.js
- shell/config/product/llmos.js
- shell/edit/management.llmos.ai.managedaddon/generic.vue
- shell/edit/management.llmos.ai.managedaddon/index.vue
- shell/edit/management.llmos.ai.managedaddon/llmos-ceph-cluster.vue
- shell/edit/node.vue
- shell/list/ceph.rook.io.cephcluster.vue
- shell/models/cluster/node.js
- shell/store/type-map.js
Add node import page & fix mirror bugs
> Add node import page & fix mirror bugs

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/edit/management.llmos.ai.managedaddon/llmos-ceph-cluster.vue
update text & ceph cluster config
> update text & ceph cluster config

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/SingleClusterInfo.vue
- shell/edit/management.llmos.ai.managedaddon/llmos-ceph-cluster.vue
- shell/list/ceph.rook.io.cephcluster.vue
- shell/utils/url.ts
Fix storage enable notification & config
> fix storage enable notification & config

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/SingleClusterInfo.vue
- shell/list/ceph.rook.io.cephcluster.vue
- shell/mixins/ceph-config.ts
- shell/utils/url.ts
Update terms & conditions link.
> update t&c link

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/BrandImage.vue
- shell/components/ClusterIconMenu.vue
- shell/components/SingleClusterInfo.vue
- shell/components/TabTitle.vue
- shell/components/llmos/WorkloadDetails.vue
- shell/components/nav/TopLevelMenu.vue
- shell/config/labels-annotations.js
- shell/config/types.js
- shell/edit/ml.llmos.ai.modelservice/index.vue
- shell/edit/ray.io.raycluster.vue
- shell/list/ceph.rook.io.cephcluster.vue
- shell/middleware/authenticated.js
- shell/mixins/llmos/ml-workload.js
- shell/models/ml.llmos.ai.modelservice.js
- shell/models/ml_workload.js
- shell/models/ray.io.raycluster.js
- shell/pages/c/_cluster/index.vue
- shell/pages/c/_cluster/llmos/index.vue
- shell/store/index.js
- shell/utils/__tests__/merge.test.ts
- shell/utils/merge.ts
- shell/utils/monitoring.js
- shell/utils/title.ts
- Add model service monitoring metrics.
- Refactor the home page with code optimization.
> Add model service monitoring & update homepage

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/TabTitle.vue
- shell/components/form/ResourceTabs/index.vue
- shell/config/product/llmos.js
- shell/config/settings.ts
- shell/edit/management.llmos.ai.managedaddon/generic.vue
- shell/edit/management.llmos.ai.managedaddon/llmos-ceph-cluster/index.vue
- shell/edit/management.llmos.ai.managedaddon/llmos-gpu-stack/index.vue
- shell/edit/management.llmos.ai.managedaddon/llmos-monitoring/index.vue
- shell/edit/management.llmos.ai.managedaddon/mixin/addon.js
- shell/edit/management.llmos.ai.setting.vue
- shell/edit/ml.llmos.ai.modelservice/index.vue
- shell/edit/ml.llmos.ai.notebook.vue
- shell/edit/ray.io.raycluster.vue
- shell/models/ml.llmos.ai.modelservice.js
- shell/models/ray.io.raycluster.js
- shell/pages/c/_cluster/monitoring/index.vue
- Add ModelService source & default image setting config
- Update tab events fetch logic & fix tab title
> Add ModelService source & fix events tabs

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/config/labels-annotations.js
- shell/models/ml.llmos.ai.modelservice.js
- shell/models/ml.llmos.ai.notebook.js
- shell/models/ml_workload.js
- shell/promptRemove/ml.llmos.ai.modelservice.vue
- shell/promptRemove/ml.llmos.ai.notebook.vue
- Add default dshm sizeLimit.
- Add prompt remove of workload volumes.
https://github.com/llmos-ai/llmos/issues/30
> Support remove volumes on workload deletion

- shell/components/ContainerResourceLimit.vue
- shell/components/SingleClusterInfo.vue
- shell/components/nav/NamespaceFilter.vue
- shell/config/settings.ts
- shell/detail/gpustack.llmos.ai.gpudevice.vue
- shell/detail/node.vue
- shell/edit/management.llmos.ai.managedaddon/llmos-gpu-stack/index.vue
- shell/edit/ray.io.raycluster.vue
- shell/mixins/llmos/ml-workload.js
- shell/models/gpustack.llmos.ai.gpudevice.js
- shell/models/ml.llmos.ai.modelservice.js
- shell/utils/container-resource.ts
- Update resource gpu/vgpu config to support volcano scheduling.
- Set admin's default ns to all namespaces.
> Update resource gpu/vgpu configs

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/config/settings.ts
- shell/edit/ml.llmos.ai.modelservice/index.vue
- shell/edit/ray.io.raycluster.vue
- shell/list/gpustack.llmos.ai.gpudevice.vue
- shell/models/ml.llmos.ai.modelservice.js
- shell/models/ml_workload.js
- shell/models/ray.io.raycluster.js
- Add model registry config support.
- Support config system images using `global-system-image-registry`
> Add model registry & support system registry config

- shell/config/labels-annotations.js
- shell/edit/ray.io.raycluster.vue
- shell/models/ml.llmos.ai.notebook.js
- shell/models/ml_workload.js
- Add pause & resume action to the ML works types.
- Fix invalid ray GPU image.
> Add ml work pause/resume action

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/CodeMirror.vue
- shell/components/NodeImportCommand.vue
- shell/config/settings.ts
- shell/edit/management.llmos.ai.setting.vue
- shell/edit/ml.llmos.ai.modelservice/index.vue
- shell/list/management.llmos.ai.setting.vue
- shell/models/pod.js
- yarn.lock
- Add JSOn view support to the settings page.
- Update view logs logic to load init-containers if it is not ready.
> Add setting json view & update view logs logic

- shell/components/form/ProjectMemberEditor.vue
- shell/edit/management.llmos.ai.token.vue
- shell/pages/account/index.vue
Fix invalid api key expired days.
> Fix invalid api key expired days

- shell/models/cluster/node.js
Fix invalid VRAM usage of the node list page
> Fix invalid vram usage of the node list page

- shell/components/NodeImportCommand.vue
Fixe add mirror cfg to node import
> Add mirror cfg to node import

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/SelectOrCreateSecret.vue
- shell/config/product/llmos.js
- shell/config/types.js
- shell/dialog/CreateSecretModal.vue
- shell/edit/ml.llmos.ai.registry.vue
- shell/list/ml.llmos.ai.registry.vue
- shell/models/ml.llmos.ai.registry.js
> Add model registry

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/edit/ml.llmos.ai.modelservice/components/ArgumentVars.vue
- shell/edit/ml.llmos.ai.modelservice/index.vue
- shell/public/index.html
Fixes #
- fix remove empty args
> fix: remove empty args

- shell/components/form/LabeledTag.vue
- shell/detail/ml.llmos.ai.dataset/FileList/FileItem.vue
- shell/detail/ml.llmos.ai.dataset/FileList/index.vue
- shell/detail/ml.llmos.ai.model/FileList/FileItem.vue
- shell/detail/ml.llmos.ai.model/FileList/index.vue
- shell/detail/ml.llmos.ai.model/index.vue
- shell/dialog/CreateDatasetVersionModal.vue
- shell/dialog/CreateFolderModal.vue
- shell/edit/ml.llmos.ai.dataset.vue
- shell/edit/ml.llmos.ai.model.vue
- shell/list/ml.llmos.ai.dataset.vue
- shell/list/ml.llmos.ai.model.vue
- shell/models/ml.llmos.ai.dataset.js
- shell/utils/dictionary.js
> fix: Lint error

- .github/workflows/lint.yaml
> fix: add pr check lint

- shell/assets/translations/zh-hans.yaml
- shell/components/nav/TopLevelMenu.vue
- shell/config/product/llmos.js
**Description:**
Update zh translation & nav weight.
> Update zh translation

- .github/workflows/build.yaml
- shell/assets/translations/zh-hans.yaml
> fix: translation

- shell/components/CopyCode.vue
> fix: code copy style

- scripts/build-hosted
> fix: change BASE URL

- package.json
- shell/components/LangFlowIcon.vue
- shell/package.json
- shell/pages/c/_cluster/apps/appManage/index.vue
- shell/yarn.lock
- yarn.lock
> feat: add langflow manage

- shell/components/CopyCode.vue
> fix: html tag

- shell/config/vllm-config.ts
- shell/edit/ml.llmos.ai.modelservice/components/ArgumentVars.vue
- shell/edit/ml.llmos.ai.modelservice/index.vue
- shell/initialize/App.vue
- shell/pages/prefs.vue
- shell/store/prefs.js
> fix: disable theme & fix bug

- shell/assets/translations/zh-hans.yaml
> feat(translations): Add chinese translation

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/nav/Type.vue
- shell/config/product/app.js
- shell/config/router/routes.js
- shell/edit/ml.llmos.ai.modelservice/index.vue
- shell/models/ml.llmos.ai.modelservice.js
- shell/pages/c/_cluster/apps/trace/index.vue
- shell/store/type-map.js
> feat: add trace page

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/SingleClusterInfo.vue
> add translations

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/config/weaviate.js
- shell/detail/agent.llmos.ai.knowledgebase.vue
- shell/models/ml.llmos.ai.localmodel.js
- shell/pages/c/_cluster/apps/document/_id.vue
> Add uid parameter to document listObjects call 

- shell/pages/auth/login.vue
> fix: add login button

- shell/assets/translations/zh-hans.yaml
- shell/components/DetailTop.vue
- shell/components/InfoBox.vue
- shell/components/NodeImportCommand.vue
> fix: style

- shell/detail/agent.llmos.ai.datacollection/FileList/index.vue
- shell/detail/ml.llmos.ai.dataset/FileList/index.vue
- shell/detail/ml.llmos.ai.model/FileList/index.vue
- shell/detail/ml.llmos.ai.model/FileList/useFileList.js
Fixes #
- Large model upload cannot start immediatly
> Support S3 upload with progress tracking

- shell/dialog/GenerateUploadScriptModal.vue
Update the script URL to use the main branch instead of a specific commit hash. Simplify token retrieval by using the response directly instead of fetching token details separately.
Fixes update script URL and simplify token retrieval
> fix: update script URL and simplify token retrieval

- shell/detail/ml.llmos.ai.dataset/FileList/index.vue
- shell/detail/ml.llmos.ai.model/FileList/useFileList.js
Add computed properties to track publish status and update button state accordingly. Remove redundant success message to prevent duplicate notifications.
Fixes #
> feat(dataset): add publish status tracking and button state

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/components/form/Dataset.vue
- shell/components/form/MatchExpressions.vue
- shell/components/form/NodeAffinity.vue
- shell/components/form/NodeScheduling.vue
- shell/components/llmos/WorkloadList.vue
- shell/config/constants.ts
- shell/detail/ml.llmos.ai.model/FileList/useFileItem.js
- shell/edit/ml.llmos.ai.modelservice/components/ArgumentVars.vue
- shell/edit/ml.llmos.ai.modelservice/index.vue
- shell/edit/ml.llmos.ai.notebook.vue
- shell/list/chat/components/ModelCard.vue
- shell/list/chat/components/SideConfig.vue
- shell/list/chat/index.vue
- shell/mixins/llmos/ml-workload.js
- shell/models/ml.llmos.ai.modelservice.js
- shell/pages/c/_cluster/apps/document/_id.vue
- shell/pages/c/_cluster/apps/document/hitTest.vue
- shell/store/chat.js
> fix: chat page bug

- shell/components/llmos/WorkloadList.vue
> fix: add detail link

- shell/components/form/LabeledInput/LabeledInput.vue
- shell/components/form/TextArea/TextAreaAutoGrow.vue
- shell/components/nav/TopLevelMenu.vue
- shell/list/chat/components/SystemPrompt.vue
> fix: hide AppMenu

- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/config/vllm-config.ts
- shell/detail/ml.llmos.ai.dataset/FileList/index.vue
- shell/dialog/GenerateUploadScriptModal.vue
- shell/models/ml.llmos.ai.model.js
> fix: upload command

- package.json
- shell/assets/translations/en-us.yaml
- shell/assets/translations/zh-hans.yaml
- shell/detail/ml.llmos.ai.dataset/FileList/index.vue
- shell/detail/ml.llmos.ai.model/FileList/useFileItem.js
- shell/dialog/GenerateUploadScriptModal.vue
- shell/edit/ml.llmos.ai.modelservice/LocalModelList.vue
- shell/list/ml.llmos.ai.localmodel.vue
- shell/models/ml.llmos.ai.localmodelversion.js
> Add snapshotting status display and translations && show local model description

- .trae/rules/project_rules.md
- shell/components/form/Dataset.vue
- shell/detail/ml.llmos.ai.dataset/FileList/index.vue
- shell/dialog/CreateDatasetVersionModal.vue
- shell/edit/ml.llmos.ai.dataset.vue
- shell/models/ml.llmos.ai.dataset.js
- Update regex patterns to extract version numbers from dataset names
- Fix version label display to show correct part of the name
- Improve registry handling and loading state in dataset edit view
Fixes #
> fix(dataset): correct version label extraction and sorting logic
